// <auto-generated />
using System;
using Bookify_API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookify_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223124902_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Bookify_API.Models.Fichier", b =>
                {
                    b.Property<int>("Idfichier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idfichier");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idfichier"));

                    b.Property<DateTime?>("DateUpload")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_upload")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdRendezVous")
                        .HasColumnType("int")
                        .HasColumnName("idRendez_vous");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("idUtilisateur");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom_fichier");

                    b.Property<string>("TypeMime")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type_mime");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Idfichier")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdRendezVous" }, "idRendez_vous");

                    b.HasIndex(new[] { "IdUtilisateur" }, "idUtilisateur");

                    b.ToTable("fichier");
                });

            modelBuilder.Entity("Bookify_API.Models.Prestataire", b =>
                {
                    b.Property<int>("IdPres")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPres");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPres"));

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<int>("IdUtili")
                        .HasColumnType("int")
                        .HasColumnName("idUtili");

                    b.Property<string>("Speciallite")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("speciallite");

                    b.HasKey("IdPres")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdUtili" }, "idUtili");

                    b.ToTable("prestataire");
                });

            modelBuilder.Entity("Bookify_API.Models.RendezVou", b =>
                {
                    b.Property<int>("IdRendezVous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRendez_vous");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRendezVous"));

                    b.Property<DateTime?>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_creation")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime")
                        .HasColumnName("date_debut");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime")
                        .HasColumnName("date_fin");

                    b.Property<int>("IdPres")
                        .HasColumnType("int")
                        .HasColumnName("idPres");

                    b.Property<int>("IdSer")
                        .HasColumnType("int")
                        .HasColumnName("idSer");

                    b.Property<int>("IdUtili")
                        .HasColumnType("int")
                        .HasColumnName("idUtili");

                    b.Property<string>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('EN_ATTENTE','ACCEPTE','REFUSE','ANNULE','TERMINE')")
                        .HasColumnName("statut")
                        .HasDefaultValueSql("'EN_ATTENTE'");

                    b.HasKey("IdRendezVous")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPres" }, "idPres");

                    b.HasIndex(new[] { "IdSer" }, "idSer");

                    b.HasIndex(new[] { "IdUtili" }, "idUtili")
                        .HasDatabaseName("idUtili1");

                    b.ToTable("rendez_vous");
                });

            modelBuilder.Entity("Bookify_API.Models.Service", b =>
                {
                    b.Property<int>("IdService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idService");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdService"));

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int>("IdPres")
                        .HasColumnType("int")
                        .HasColumnName("idPres");

                    b.Property<string>("Nom")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("prix");

                    b.HasKey("IdService")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPres" }, "idPres")
                        .HasDatabaseName("idPres1");

                    b.ToTable("service");
                });

            modelBuilder.Entity("Bookify_API.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUtilisateur");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("adresse");

                    b.Property<DateTime?>("CreerA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creerA")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nomComplet");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("passwordHash");

                    b.Property<DateTime?>("ResetCodeExpiry")
                        .HasColumnType("datetime")
                        .HasColumnName("resetCodeExpiry");

                    b.Property<string>("ResetPasswordCode")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("resetCode");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('CLIENT','PRESTATAIRE','ADMIN')")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'CLIENT'");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telephone");

                    b.HasKey("IdUtilisateur")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.ToTable("utilisateur");
                });

            modelBuilder.Entity("Bookify_API.Models.Fichier", b =>
                {
                    b.HasOne("Bookify_API.Models.RendezVou", "IdRendezVousNavigation")
                        .WithMany("Fichiers")
                        .HasForeignKey("IdRendezVous")
                        .IsRequired()
                        .HasConstraintName("fichier_ibfk_1");

                    b.HasOne("Bookify_API.Models.Utilisateur", "IdUtilisateurNavigation")
                        .WithMany("Fichiers")
                        .HasForeignKey("IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("fichier_ibfk_2");

                    b.Navigation("IdRendezVousNavigation");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("Bookify_API.Models.Prestataire", b =>
                {
                    b.HasOne("Bookify_API.Models.Utilisateur", "IdUtiliNavigation")
                        .WithMany("Prestataires")
                        .HasForeignKey("IdUtili")
                        .IsRequired()
                        .HasConstraintName("prestataire_ibfk_1");

                    b.Navigation("IdUtiliNavigation");
                });

            modelBuilder.Entity("Bookify_API.Models.RendezVou", b =>
                {
                    b.HasOne("Bookify_API.Models.Prestataire", "IdPresNavigation")
                        .WithMany("RendezVous")
                        .HasForeignKey("IdPres")
                        .IsRequired()
                        .HasConstraintName("rendez_vous_ibfk_2");

                    b.HasOne("Bookify_API.Models.Service", "IdSerNavigation")
                        .WithMany("RendezVous")
                        .HasForeignKey("IdSer")
                        .IsRequired()
                        .HasConstraintName("rendez_vous_ibfk_3");

                    b.HasOne("Bookify_API.Models.Utilisateur", "IdUtiliNavigation")
                        .WithMany("RendezVous")
                        .HasForeignKey("IdUtili")
                        .IsRequired()
                        .HasConstraintName("rendez_vous_ibfk_1");

                    b.Navigation("IdPresNavigation");

                    b.Navigation("IdSerNavigation");

                    b.Navigation("IdUtiliNavigation");
                });

            modelBuilder.Entity("Bookify_API.Models.Service", b =>
                {
                    b.HasOne("Bookify_API.Models.Prestataire", "IdPresNavigation")
                        .WithMany("Services")
                        .HasForeignKey("IdPres")
                        .IsRequired()
                        .HasConstraintName("service_ibfk_1");

                    b.Navigation("IdPresNavigation");
                });

            modelBuilder.Entity("Bookify_API.Models.Prestataire", b =>
                {
                    b.Navigation("RendezVous");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Bookify_API.Models.RendezVou", b =>
                {
                    b.Navigation("Fichiers");
                });

            modelBuilder.Entity("Bookify_API.Models.Service", b =>
                {
                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("Bookify_API.Models.Utilisateur", b =>
                {
                    b.Navigation("Fichiers");

                    b.Navigation("Prestataires");

                    b.Navigation("RendezVous");
                });
#pragma warning restore 612, 618
        }
    }
}
