// <auto-generated />
using System;
using Bookify_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookify_API.Migrations.BookifyDb
{
    [DbContext(typeof(BookifyDbContext))]
    [Migration("20260609161000_AddFavoris")]
    partial class AddFavoris
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Bookify_API.Models.Disponibilite", b =>
                {
                    b.Property<int>("IdDispo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDispo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDispo"));

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("disponible");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time(6)")
                        .HasColumnName("heureDebut");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time(6)")
                        .HasColumnName("heureFin");

                    b.Property<int>("IdPres")
                        .HasColumnType("int")
                        .HasColumnName("idPres");

                    b.Property<string>("JourSemaine")
                        .IsRequired()
                        .HasColumnType("enum('Lun','Mar','Mer','Jeu','Ven','Sam','Dim')")
                        .HasColumnName("jourSemaine");

                    b.HasKey("IdDispo")
                        .HasName("PRIMARY");

                    b.HasIndex("IdPres");

                    b.ToTable("disponibilite", (string)null);
                });

            modelBuilder.Entity("Bookify_API.Models.Favori", b =>
                {
                    b.Property<int>("IdFavori")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idFavori");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdFavori"));

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime")
                        .HasColumnName("dateAjout");

                    b.Property<int>("IdPrestataire")
                        .HasColumnType("int")
                        .HasColumnName("idPrestataire");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("idUtilisateur");

                    b.HasKey("IdFavori")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPrestataire" }, "idPrestataire_favoris");

                    b.HasIndex(new[] { "IdUtilisateur" }, "idUtilisateur_favoris");

                    b.ToTable("favoris", (string)null);
                });

            modelBuilder.Entity("Bookify_API.Models.Fichier", b =>
                {
                    b.Property<int>("Idfichier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idfichier");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idfichier"));

                    b.Property<DateTime?>("DateUpload")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_upload")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdRendezVous")
                        .HasColumnType("int")
                        .HasColumnName("idRendez_vous");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("idUtilisateur");

                    b.Property<string>("NomFichier")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom_fichier");

                    b.Property<string>("TypeMime")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type_mime");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Idfichier")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdRendezVous" }, "idRendez_vous");

                    b.HasIndex(new[] { "IdUtilisateur" }, "idUtilisateur");

                    b.ToTable("fichier", (string)null);
                });

            modelBuilder.Entity("Bookify_API.Models.Message", b =>
                {
                    b.Property<int>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMessage");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMessage"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenu");

                    b.Property<DateTime?>("EnvoieA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("envoieA")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdEnvoyeur")
                        .HasColumnType("int")
                        .HasColumnName("idEnvoyeur");

                    b.Property<int>("IdReceveur")
                        .HasColumnType("int")
                        .HasColumnName("idReceveur");

                    b.Property<bool>("Lu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("lu");

                    b.HasKey("IdMessage")
                        .HasName("PRIMARY");

                    b.HasIndex("IdEnvoyeur");

                    b.HasIndex("IdReceveur");

                    b.ToTable("message", (string)null);
                });

            modelBuilder.Entity("Bookify_API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsRead");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Message");

                    b.Property<int?>("RendezVousId")
                        .HasColumnType("int")
                        .HasColumnName("RendezVousId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Title");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int")
                        .HasColumnName("UtilisateurId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("RendezVousId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Bookify_API.Models.Prestataire", b =>
                {
                    b.Property<int>("IdPres")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPres");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPres"));

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("Categorie")
                        .HasColumnType("enum('Sante & medical','Beaute & Bien etre','Services profesionnels','Service techniques')")
                        .HasColumnName("categorie");

                    b.Property<int>("IdUtili")
                        .HasColumnType("int")
                        .HasColumnName("idUtili");

                    b.Property<decimal?>("Note")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)")
                        .HasColumnName("note")
                        .HasDefaultValueSql("'0.0'");

                    b.Property<string>("Speciallite")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("speciallite");

                    b.HasKey("IdPres")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdUtili" }, "idUtili");

                    b.ToTable("prestataire", (string)null);
                });

            modelBuilder.Entity("Bookify_API.Models.Prestatairephoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("PrestataireId")
                        .HasColumnType("int")
                        .HasColumnName("prestataireId");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PrestataireId" }, "prestataireId");

                    b.ToTable("prestatairephotos", (string)null);
                });

            modelBuilder.Entity("Bookify_API.Models.RendezVou", b =>
                {
                    b.Property<int>("IdRendezVous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRendez_vous");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRendezVous"));

                    b.Property<DateTime?>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_creation")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime")
                        .HasColumnName("date_debut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime")
                        .HasColumnName("date_fin");

                    b.Property<int>("IdPres")
                        .HasColumnType("int")
                        .HasColumnName("idPres");

                    b.Property<int>("IdSer")
                        .HasColumnType("int")
                        .HasColumnName("idSer");

                    b.Property<int>("IdUtili")
                        .HasColumnType("int")
                        .HasColumnName("idUtili");

                    b.Property<string>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('EN_ATTENTE','ACCEPTE','REFUSE','ANNULE','TERMINE')")
                        .HasColumnName("statut")
                        .HasDefaultValueSql("'EN_ATTENTE'");

                    b.HasKey("IdRendezVous")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPres" }, "idPres");

                    b.HasIndex(new[] { "IdSer" }, "idSer");

                    b.HasIndex(new[] { "IdUtili" }, "idUtili")
                        .HasDatabaseName("idUtili1");

                    b.ToTable("rendez_vous", (string)null);
                });

            modelBuilder.Entity("Bookify_API.Models.Service", b =>
                {
                    b.Property<int>("IdService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idService");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdService"));

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int>("IdPres")
                        .HasColumnType("int")
                        .HasColumnName("idPres");

                    b.Property<string>("Nom")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom");

                    b.Property<decimal?>("Prix")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("prix");

                    b.HasKey("IdService")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPres" }, "idPres")
                        .HasDatabaseName("idPres1");

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("Bookify_API.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUtilisateur");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("adresse");

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("avatar");

                    b.Property<DateTime?>("CreerA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creerA")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nomComplet");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("passwordHash");

                    b.Property<DateTime?>("ResetCodeExpiry")
                        .HasColumnType("datetime")
                        .HasColumnName("resetCodeExpiry");

                    b.Property<string>("ResetPasswordCode")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("resetPasswordCode");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('CLIENT','PRESTATAIRE','ADMIN')")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'CLIENT'");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telephone");

                    b.HasKey("IdUtilisateur")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.ToTable("utilisateur", (string)null);
                });

            modelBuilder.Entity("Bookify_API.Models.Disponibilite", b =>
                {
                    b.HasOne("Bookify_API.Models.Prestataire", "IdPresNavigation")
                        .WithMany()
                        .HasForeignKey("IdPres")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("disponibilite_ibfk_1");

                    b.Navigation("IdPresNavigation");
                });

            modelBuilder.Entity("Bookify_API.Models.Favori", b =>
                {
                    b.HasOne("Bookify_API.Models.Prestataire", "Prestataire")
                        .WithMany()
                        .HasForeignKey("IdPrestataire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favoris_prestataire");

                    b.HasOne("Bookify_API.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favoris_utilisateur");

                    b.Navigation("Prestataire");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Bookify_API.Models.Fichier", b =>
                {
                    b.HasOne("Bookify_API.Models.RendezVou", "IdRendezVousNavigation")
                        .WithMany("Fichiers")
                        .HasForeignKey("IdRendezVous")
                        .HasConstraintName("fichier_ibfk_1");

                    b.HasOne("Bookify_API.Models.Utilisateur", "IdUtilisateurNavigation")
                        .WithMany("Fichiers")
                        .HasForeignKey("IdUtilisateur")
                        .HasConstraintName("fichier_ibfk_2");

                    b.Navigation("IdRendezVousNavigation");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("Bookify_API.Models.Message", b =>
                {
                    b.HasOne("Bookify_API.Models.Utilisateur", "IdEnvoyeurNavigation")
                        .WithMany()
                        .HasForeignKey("IdEnvoyeur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("message_ibfk_1");

                    b.HasOne("Bookify_API.Models.Utilisateur", "IdReceveurNavigation")
                        .WithMany()
                        .HasForeignKey("IdReceveur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("message_ibfk_2");

                    b.Navigation("IdEnvoyeurNavigation");

                    b.Navigation("IdReceveurNavigation");
                });

            modelBuilder.Entity("Bookify_API.Models.Notification", b =>
                {
                    b.HasOne("Bookify_API.Models.RendezVou", "RendezVous")
                        .WithMany()
                        .HasForeignKey("RendezVousId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bookify_API.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notifications_ibfk_1");

                    b.Navigation("RendezVous");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Bookify_API.Models.Prestataire", b =>
                {
                    b.HasOne("Bookify_API.Models.Utilisateur", "IdUtiliNavigation")
                        .WithMany("Prestataires")
                        .HasForeignKey("IdUtili")
                        .IsRequired()
                        .HasConstraintName("prestataire_ibfk_1");

                    b.Navigation("IdUtiliNavigation");
                });

            modelBuilder.Entity("Bookify_API.Models.Prestatairephoto", b =>
                {
                    b.HasOne("Bookify_API.Models.Prestataire", "Prestataire")
                        .WithMany("Prestatairephotos")
                        .HasForeignKey("PrestataireId")
                        .HasConstraintName("prestatairephotos_ibfk_1");

                    b.Navigation("Prestataire");
                });

            modelBuilder.Entity("Bookify_API.Models.RendezVou", b =>
                {
                    b.HasOne("Bookify_API.Models.Prestataire", "IdPresNavigation")
                        .WithMany("RendezVous")
                        .HasForeignKey("IdPres")
                        .IsRequired()
                        .HasConstraintName("rendez_vous_ibfk_2");

                    b.HasOne("Bookify_API.Models.Service", "IdSerNavigation")
                        .WithMany("RendezVous")
                        .HasForeignKey("IdSer")
                        .IsRequired()
                        .HasConstraintName("rendez_vous_ibfk_3");

                    b.HasOne("Bookify_API.Models.Utilisateur", "IdUtiliNavigation")
                        .WithMany("RendezVous")
                        .HasForeignKey("IdUtili")
                        .IsRequired()
                        .HasConstraintName("rendez_vous_ibfk_1");

                    b.Navigation("IdPresNavigation");

                    b.Navigation("IdSerNavigation");

                    b.Navigation("IdUtiliNavigation");
                });

            modelBuilder.Entity("Bookify_API.Models.Service", b =>
                {
                    b.HasOne("Bookify_API.Models.Prestataire", "IdPresNavigation")
                        .WithMany("Services")
                        .HasForeignKey("IdPres")
                        .IsRequired()
                        .HasConstraintName("service_ibfk_1");

                    b.Navigation("IdPresNavigation");
                });

            modelBuilder.Entity("Bookify_API.Models.Prestataire", b =>
                {
                    b.Navigation("Prestatairephotos");

                    b.Navigation("RendezVous");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Bookify_API.Models.RendezVou", b =>
                {
                    b.Navigation("Fichiers");
                });

            modelBuilder.Entity("Bookify_API.Models.Service", b =>
                {
                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("Bookify_API.Models.Utilisateur", b =>
                {
                    b.Navigation("Fichiers");

                    b.Navigation("Prestataires");

                    b.Navigation("RendezVous");
                });
#pragma warning restore 612, 618
        }
    }
}
